version: "3"
services:
  openplc:
    build: ./
    ports:
      - "8080:8080" #SCADA UI, http
      - "502:502" #Modbus
      - "20000:20000"
      - "44818:44818"
    restart: always
  tcpdump:
    image: nicolaka/netshoot
    volumes:
      - oplc_dumplog:/etc/data
    depends_on:
      - openplc
    command: tcpdump -i eth0 -w /etc/data/bris_conpot.pcap
    network_mode: service:openplc
volumes:
  oplc_dumplog:
