version: "3"
services:
  tcpdump:
    image: nicolaka/netshoot
    ports:
      - "80:8800" #SCADA UI, http
      - "102:10201" #S7Comm
      - "502:5020" #Modbus
      - "161:16100/udp" #SNMP
      - "47808:47808/udp" #Bacnet
      - "623:6230/udp" #IPMI
      - "21:2121" #FTP
      - "69:6969/udp" #TFTP
      - "44818:44818" #EN/IP
      - "10001:10001"
    expose:
        - "8800"
        - "10201"
        - "5020"
        - "16100"
        - "47808"
        - "6230"
        - "2121"
        - "6969"
        - "44818"
        - "10001"
    restart: always
    volumes:
      - blanklog:/etc/data
    command: tcpdump -i eth0 -w /etc/data/blankvm.pcap
volumes:
  blanklog:
